### ISSUE TITLE
weird error when using tokio-timer with tokio-tungstenite

### ISSUE THREAD

**Issue by bbigras** [tokio-rs/tokio-timer#20]
Adding `extern crate tokio_timer;` to https://github.com/snapview/tokio-tungstenite/blob/60f9d3eedde7992d06b9debd24438bebdf820e8d/examples/server.rs breaks the build with this error:

```
> cargo build 
   Compiling test-tung-server v0.1.0 (file:///home/bbigras/dev/rust/tests/test-tung-server)
error[E0283]: type annotations required: cannot resolve `(): std::convert::From<_>`
  --> src/main.rs:77:36
   |
77 |                 let ws_writer = rx.fold(sink, |mut sink, msg| {
   |                                    ^^^^

error: aborting due to previous error

error: Could not compile `test-tung-server`.
```

I reported this first to tokio-tungstenite (see https://github.com/snapview/tokio-tungstenite/issues/8) but I filled it here as suggested in case we could learn more what happened.

rustc 1.17.0-nightly (7846dbe0c 2017-03-26)
futures 0.1.12
tokio-core 0.1.6
tokio-timer 0.1.1
tokio-tungstenite 0.1.2
tungstenite 0.2.1

**Comment by carllerche** [comment]
This is probably due to tokio-timer providing extra implementations such that rust can't do inference where it did before. If anything, this would be a rustc issue (though I don't known if they would consider it a bug or feature). 

I'm going to close this for now. If it turns out to be a tokio-timer issue, feel free to reopen.

**Comment by application-developer-DA** [comment]
> This is probably due to tokio-timer providing extra implementations such that rust can't do inference where it did before.

Yes, it seems like that. Do you know which implementations could cause this? (I'm just curious what could break the type inference there)

More precisely the problem was reported at this line: https://github.com/snapview/tokio-tungstenite/blob/master/examples/server.rs#L96

Without `tokio-timer` the code compiles without any problems, but after adding `tokio-timer` it fails telling that it cannot convert the error type of the closure to `()`. And so as a workaround [I had to specify the return value explicitly](https://github.com/snapview/tokio-tungstenite/issues/8#issuecomment-292122012).

P.S.: I know that most likely it's not a tokio-timer issue, but the "issue" with rustc, I thought that maybe you know which implementations inside tokio-timer may lead to this issue.
